---
title: "Dynamic Assessment of Self-Efficacy Predicts Future Alcohol Use" 
author: "Gaylen Fronk, M.S."
institute: "University of Wisconsin-Madison"
format: 
  revealjs:
    scrollable: true
    chalkboard: false
    css: slides.css
    background-color: dark-gray
fig-cap-location: top
editor_options: 
  chunk_output_type: console
---
## Acknowledgements {.smaller}

:::: {.columns}

::: {.column width="40%"}
- Project Co-Authors
  - Ariela Papp
  - Kendra Wyant
  - Sarah Sant'Ana
  - John Curtin (PI)
:::

::: {.column width="60%"}
- Parent Project
  - Susan Wanta (project administration, data curation)
  - Candace Lightheart (data collection)
  - Kerry Keiser (data collection)
  - Megan Schultz (data collection)
  - Jill Nagler (data collection)
  - Chris Gioia (clinical supervision)
  - Xiaojin (Jerry) Zhu (project conceptualization, analyses)
:::

::::

- Funding
  - This research was supported by grants from the NIAAA (R01 AA024391; Curtin) and the NIDA (R01 DA047315; Curtin)
  - This investigator was supported by a grant from the NIDA (F31 DA056144; Fronk)
  
## Background...

- In our study: "How likely are you to drink alcohol in the next week?"

## Self-monitoring during AUD recovery

[Self-monitoring]{.yellow} is a tool to increase conscious awareness about one's own *present* or *future* behavior

:::{.notes}
Self-monitoring = insight = confidence/likelihood of behaviors

It can bring about awareness of current behaviors, but it can also encourage thinking about the likelihood of future behaviors
:::

## Self-monitoring during AUD recovery

[Self-monitoring]{.yellow} is a tool to increase conscious awareness about one's own present or [*future*]{.yellow} behavior

:::{.notes}
In the case of AUD, self-monitoring is often used to increase awareness about CURRENT RISK of FUTURE ALCOHOL USE
:::

## Self-monitoring during AUD recovery

- Self-monitoring is...
  - Encouraged by clinicians
  - Prompted by many self-help tools/apps/etc.
  - Considered to be a productive component of CBT in the treatment of substance use disorders

:::{.notes}
There is a strongly held belief that self-monitoring is valuable and even necessary tool during recovery from alcohol use disorder (AUD) and other substance use disorders
:::
## Static measurement

- Self-monitoring has traditionally been measured statically
  - Measures like the Alcohol Abstinence Self-Efficacy Scale (AASE) are often used to assess an individual's "long-term" likelihood of remaining abstinent
  - Scores from measures like the AASE may be used at the end of treatment/end of study/etc. to estimate an individual's future likelihood of staying abstinent

It is **unclear how well static measures like the AASE predict future lapse and relapse outcomes**.

:::{.footer}
reference for AASE brief version
:::

## Recovery as a dynamic process

- Risk of lapse/relapse is best understood **dynamically**
  - Relapse prevention model has been updated to reflect dynamic processes
  - Fluctuating risk over time due to fluctuating proximal and distal risk factors that interact fluidly with one another
- Thus, *self-monitoring dynamic risk of lapse likely requires dense, dynamic assessment to be effective*

:::{.notes}
Static or one-time measurement stands in conflict with what we know about the dynamic relapse prevention model
:::

## Dynamic self-monitoring via EMA

- Ecological momentary assessment (EMA) offers a method by which individuals can self-monitor densely and longitudinally
- Continuous monitoring with EMA can be embedded within a digital therapeutic context that can allow:
  - Simultaneous monitoring of other risk factors
  - Access to supports and tools to be used throughout recovery
  
## Dynamic self-monitoring via EMA

> "How likely are you to drink alcohol in the next week?"

Self-monitoring was...
- **Dynamic**: Assessments occurred *daily*
- **Cued**: Individuals were *prompted* to reflect on their risk
- **Contextualized**: Self-monitoring question was situated within a 10-item EMA
  - 6 questions assessing risk factors 
  - 2 additional questions monitoring future behavior
  - Self-monitoring item was the *final* item, requiring reflection on 9 relevant risk factors prior to answering

:::{.notes}
In the current study, individuals self-monitored their risk for lapse back to alcohol use via daily EMA surveys that included the question "How likely are you to drink alcohol in the next week"

Dynamic assessment - daily EMA allows for frequent updating

(e.g., craving, affect)

(e.g., likelihood of experiencing a stressful event)
:::

## Purpose

:::{.columns}

::::{.column, width="40%"}
The purpose of this project is to determine:

1. How accurately individuals could self-monitor their risk of alcohol lapse in the next week

2. Whether dynamic self-monitoring offers greater predictive value than static risk assessment

3. Whether models that take advantage of full EMA data and feature engineering can predict lapse risk more accurately than self-monitoring alone

::::

::::{.column, width="60%"}
<!--progress through brief explanations of each  
1. brief overview: put question back up, model built from single predictor (kept "raw") matched to outcome of the same 1-week window, did they actually lapse. model performance = index of accuracy of their predictions

2. compared that 1-predictor model to a model built from a single AASE measurement at study intake. 

3. built model using all EMA data from the same study period (i.e., all questions) with more advanced feature engineering techniques to predict same 1-week outcome windows. compared how well we can predict using this "full" model to the dynamic assessment only model (how much better can we do if we take all the data into account, what else does it allow us to do with the outcome [treatment recs])
-->
::::

:::

<!--CONSIDER: "all" methods details upfront? or only necessary details for each purpose Q? might be less overwhelming that way, and not jumping back and forth re: relevance of methods details -->

## Participants

brief bulleted overview

include demo table (take from Ariela's poster) or just bulleted notes about demo characteristics

## EMA

more methods details here on EMA, all items, highlight SM question again

discuss 4x daily component

timing

## Lapse labels

1-week windows tied to morning EMA submission

procedure for creating labeled windows

N windows lapse/no lapse

## Analyses insight only models

## AASE

scoring

time period it assesses for

## Analyses model comparisons purpose 2

## Feature engineering

## Analyses model comparisons purpose 3


